# Generated by Django 3.2.18 on 2023-05-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('image', models.CharField(max_length=25)),
                ('nom', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
