# Generated by Django 3.2.18 on 2023-06-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20230619_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='member1',
            field=models.CharField(default='member1', max_length=100),
        ),
        migrations.AddField(
            model_name='workspace',
            name='member2',
            field=models.CharField(default='member2', max_length=100),
        ),
        migrations.AddField(
            model_name='workspace',
            name='member3',
            field=models.CharField(default='member3', max_length=100),
        ),
        migrations.AddField(
            model_name='workspace',
            name='member4',
            field=models.CharField(default='member4', max_length=100),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
