# Generated by Django 3.2.18 on 2023-06-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_workspace_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='image',
        ),
    ]
