# Generated by Django 3.2.18 on 2023-06-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20230623_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='member1',
            field=models.CharField(default='member1', max_length=100),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='member2',
            field=models.CharField(default='member2', max_length=100),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='member3',
            field=models.CharField(default='member3', max_length=100),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='member4',
            field=models.CharField(default='member4', max_length=100),
        ),
    ]
