# Generated by Django 3.2.18 on 2023-06-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_remove_workspace_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
